name: Build Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Extract version and commit
        id: vars
        run: |
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build binary
        shell: bash
        run: |
          mkdir -p dist
          GOOS=$(echo "${{ matrix.os }}" | sed 's/-latest//')
          GOARCH=amd64

          case "$GOOS" in
            ubuntu)   GOOS=linux   ;;
            macos)    GOOS=darwin  ;;
            windows)  GOOS=windows ;;
          esac

          EXT=""
          if [ "$GOOS" = "windows" ]; then EXT=".exe"; fi

          echo "Building for $GOOS/$GOARCH..."
          GOOS=$GOOS GOARCH=$GOARCH \
          go build -ldflags "-X github.com/jkvn/Switchy/internal/core.Version=${{ steps.vars.outputs.version }} -X github.com/jkvn/Switchy/internal/core.Commit=${{ steps.vars.outputs.commit }}" \
          -o dist/switchy-${GOOS}-${GOARCH}${EXT} .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: switchy-${{ matrix.os }}
          path: dist/switchy-*